### ISSUE TITLE
A nice way to lint `.vue` files with Stylelint?

### ISSUE THREAD

**Issue by oe** [vuejs/011.vuejs.org#6]
@dan-gamble commented on [Fri Aug 05 2016](https://github.com/vuejs/vue-loader/issues/303)

I noticed this was attempted: https://github.com/vuejs-templates/webpack/pull/154 and closed (For good reason)

But i wondered if anyone has a setup for this currently?

---

@xmoki commented on [Mon Sep 05 2016](https://github.com/vuejs/vue-loader/issues/303#issuecomment-244641248)

I think is possible to do it with htmlhint, but currently only supports jshint and csslint, maybe if someone can make a htmlhint rule for stylelint.

---

@JounQin commented on [Mon Sep 05 2016](https://github.com/vuejs/vue-loader/issues/303#issuecomment-244647338)

Actually we could use `<style src="/path/of/style/file"/>` then just lint the style file as usual.

---

@yisibl commented on [Wed Nov 09 2016](https://github.com/vuejs/vue-loader/issues/303#issuecomment-259328193)

1. Touch `.stylelintrc`
   
   ``` json
   {
     "processors": ["stylelint-processor-html"],
     "extends": "stylelint-config-standard"
   }
   ```
2.   Install
   
   ``` json
     npm i stylelint -D
     npm i stylelint-processor-html -D
     npm i stylelint-config-standard -D
   ```
3. Add `lint:css` to `package.json`
   
   ``` json
   "scripts": {
     "lint:css": "stylelint '**/*.vue' --syntax scss"
   },
   ```
4. `npm run lint:css` 👻 

---

@dan-gamble commented on [Mon Nov 14 2016](https://github.com/vuejs/vue-loader/issues/303#issuecomment-260214268)

@yisibl that works for me, swear i tried this before!

---

@scottsandersdev commented on [Tue Dec 06 2016](https://github.com/vuejs/vue-loader/issues/303#issuecomment-264910855)

I'm wondering if there's a way to get stylelint to report this to sublimelinter, although it works great from the command line, it doesn't work actively while typing in sublime. Have you or anyone else had any luck with that? Also, @yisibl thanks for posting this, helped me get started.

---

@bkzl commented on [Sun Feb 12 2017](https://github.com/vuejs/vue-loader/issues/303#issuecomment-279211862)

For the record, this is working configuration for webpack:

1. Install:

```sh
npm i --save-dev stylelint stylelint-processor-html stylelint-config-standard stylelint-webpack-plugin
```

2. Create `.stylelintrc`

```js
{
 "processors": ["stylelint-processor-html"],
 "extends": "stylelint-config-standard"
}
```

3. Load stylelint-webpack-plugin (in `build/webpack.dev.conf.js` for Vue webpack template)

```js
//...
var StylelintPlugin = require('stylelint-webpack-plugin')

{
  //...
  plugins: [
    //...
    new StylelintPlugin({
      files: ['**/*.vue']
    })
  ]
}
```

I published [an article](https://medium.com/lost-bananas/linting-css-in-vue-files-6bb20faac0f2) which includes both solutions and explains two additional things (configuration rules and errors when starting the dev server).

---

@wenkanglin commented on [Tue Feb 14 2017](https://github.com/vuejs/vue-loader/issues/303#issuecomment-279628002)

@bkzl i follow your config, use the `stylelint-webpack-plugin`, it can work, but the line number of error reporter is incorrect for `.vue` file.

![qq 20170214151913](https://cloud.githubusercontent.com/assets/21100124/22919258/c4aa316a-f2c9-11e6-9695-a0ec8ee54cca.png)

---

@bkzl commented on [Wed Feb 15 2017](https://github.com/vuejs/vue-loader/issues/303#issuecomment-279883227)

@wenkanglin I immediately fix these errors while I code so I didn't even notice that. There is a corresponding issue: ccbikai/stylelint-processor-html/issues/1

---

@repsac-by commented on [Fri Feb 24 2017](https://github.com/vuejs/vue-loader/issues/303#issuecomment-282131495)

try `@mapbox/stylelint-processor-arbitrary-tags`   instead   `stylelint-processor-html`

---

@jing2si commented on [Thu May 25 2017](https://github.com/vuejs/vue-loader/issues/303#issuecomment-303951106)

> "scripts": {
>     "lint:css": "stylelint '**/*.vue' --syntax scss"
> },

Can not add single quotation marks in windows. Otherwise it will report the following error.
> Error: '**/*.vue' does not match any files
>  at globby.then.filePaths

The following setting worked well in windows 10

```
"scripts": {
  "lint:css": "stylelint **/*.vue"
},
```

---

@gucong3000 commented on [Fri Jul 28 2017](https://github.com/vuejs/vue-loader/issues/303#issuecomment-318621481)

`stylelint-webpack-plugin` or `stylelint-processor-html` not support automatically fixes.
Related:

#839
stylelint/stylelint#2596

**Comment by gucong3000** [comment]
Related:
https://github.com/vuejs-templates/webpack/pull/842
